"""Bonus mini-product UI — Lab 17 memory agent demo (STUDENT starter).

Full +10 (live demo) when ALL of these work:

1. Load test cases from `data/sessions.json` (public). Golden file optional.
2. Pick a case; UI shows query, expected layer, user_id, thread_id.
3. Run student memory retrieval and show per-layer evidence + merged context.
4. Chat box continues as that user/thread: append turns, retrieve again, keep
   history, and the assistant reply is generated by Gemini grounded in the
   retrieved memory context (gemini-2.5-flash-lite by default).

The page shell, budget metrics, and Gemini chat are wired for you. Your job is
the ONE function marked `BONUS TODO`: `retrieve_for_case(...)`.

Run:

    docker compose run --rm --service-ports app \\
      streamlit run src/demo_ui.py --server.address 0.0.0.0 --server.port 8501

or locally:  streamlit run src/demo_ui.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import streamlit as st

from src.config import settings
from src.llm import SYSTEM_INSTRUCTION, gemini_available, generate_reply
from src.memory_student import StudentMemory
from src.short_term import ShortTermMemory
from src.utils import GOLDEN_PATH, load_dataset, load_json
from src.zep_common import get_zep_client

LAYER_COLORS = {
    "short_term": "#2563eb",
    "long_term": "#059669",
    "episodic": "#d97706",
    "semantic": "#7c3aed",
}

# --- Chat backend -----------------------------------------------------------
# src/llm.py only speaks Gemini. This lab machine has an OpenAI key instead, so
# an OpenAI-compatible path is added HERE (demo_ui.py is a file students may
# edit) rather than by patching the locked starter module. Uses `requests`,
# already a dependency, so requirements.txt / the image stay untouched.
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1")


def openai_available() -> bool:
    return bool(os.getenv("OPENAI_API_KEY"))


def chat_backend() -> str:
    if openai_available():
        return f"OpenAI · {OPENAI_MODEL}"
    if gemini_available():
        return f"Gemini · {settings.gemini_model}"
    return "none (showing raw context)"


def openai_reply(
    memory_context: str,
    history: list[dict[str, str]],
    user_message: str,
    *,
    attempts: int = 3,
) -> str:
    """Grounded reply via an OpenAI-compatible chat endpoint.

    Same contract as llm.generate_reply: the model may only use the retrieved
    memory context, so the UI still demonstrates memory rather than model
    world-knowledge.

    Retries transient TLS/connection failures. This lab machine sits behind
    something that intermittently breaks the handshake to api.openai.com
    (observed: "TLSV1_ALERT_PROTOCOL_VERSION", and the same symptom against
    registry-1.docker.io), so a single dropped handshake must not take the demo
    down mid-presentation.
    """
    import time

    import requests

    messages = [{"role": "system", "content": SYSTEM_INSTRUCTION}]
    for msg in history:
        role = "user" if msg.get("role") == "user" else "assistant"
        if msg.get("content"):
            messages.append({"role": role, "content": msg["content"]})
    messages.append(
        {
            "role": "user",
            "content": (
                "Retrieved memory context for this turn:\n"
                "-------------------------------------\n"
                f"{memory_context.strip() or '(no memory retrieved)'}\n"
                "-------------------------------------\n\n"
                f"User message: {user_message}"
            ),
        }
    )

    last_error: Exception | None = None
    for attempt in range(attempts):
        try:
            response = requests.post(
                f"{OPENAI_BASE_URL}/chat/completions",
                headers={"Authorization": f"Bearer {os.environ['OPENAI_API_KEY']}"},
                json={
                    "model": OPENAI_MODEL,
                    "messages": messages,
                    "temperature": 0.3,
                    "max_tokens": 800,
                },
                timeout=60,
            )
            response.raise_for_status()
            return response.json()["choices"][0]["message"]["content"].strip()
        except (
            requests.exceptions.SSLError,
            requests.exceptions.ConnectionError,
            requests.exceptions.Timeout,
        ) as exc:
            last_error = exc
            if attempt < attempts - 1:
                time.sleep(2 * (attempt + 1))

    raise RuntimeError(
        f"Could not reach {OPENAI_BASE_URL} after {attempts} attempts: {last_error}. "
        "The TLS handshake is being broken by something on the network path "
        "(antivirus/firewall TLS inspection, VPN or proxy) — retrieval above is "
        "unaffected, only the chat reply needs this call."
    ) from last_error


CSS = """
<style>
.block-container { padding-top: 2rem; max-width: 1200px; }
.lab-badge {
    display:inline-block; padding:2px 10px; border-radius:999px;
    color:#fff; font-size:0.75rem; font-weight:600; letter-spacing:.02em;
    margin-right:6px;
}
.lab-card {
    border:1px solid rgba(128,128,128,.25); border-radius:12px;
    padding:14px 16px; margin-bottom:12px; background:rgba(127,127,127,.06);
}
.lab-kv { font-size:0.85rem; opacity:.85; }
.lab-kv b { opacity:1; }
.stChatMessage { border-radius:12px; }
</style>
"""


def load_cases() -> list[dict[str, Any]]:
    cases = list(load_dataset()["evaluations"])
    if GOLDEN_PATH.exists():
        try:
            cases.extend(load_json(GOLDEN_PATH).get("evaluations") or [])
        except Exception:
            pass
    return cases


def format_case(case: dict[str, Any]) -> str:
    return f"{case['id']} · {case['expected_layer']} · {case['user_id']}"


def layer_badge(layer: str) -> str:
    color = LAYER_COLORS.get(layer, "#475569")
    return f'<span class="lab-badge" style="background:{color}">{layer}</span>'


def retrieve_for_case(
    memory: StudentMemory,
    case: dict[str, Any],
    extra_messages: list[dict[str, str]],
) -> dict[str, Any]:
    """BONUS TODO: run student retrieval for the loaded case.

    Return a dict with keys:
      - "merged_context": str  (StudentMemory.assemble_context output)
      - "layers": dict[str, str]  (per-layer evidence: short_term/long_term/
                                   episodic/semantic)
      - "budget": dict  (the breakdown from assemble_context)

    Hints:
      * Build short_term from case["fixture_messages"] if present, else from
        the matching user/thread messages in data/sessions.json, plus
        extra_messages. E01 has no fixture — it uses thread minh-s1.
      * Decide which durable layers to fetch from case["expected_layer"] (or
        case["retrieve_layers"] for "mixed"), then call
        memory.retrieve_long_term / retrieve_episodic / retrieve_semantic.
      * Keep user_id and thread_id from the loaded case.
      * Finish with memory.assemble_context(layers).
    """
    user_id = case.get("user_id", "")
    query = case.get("query", "")

    # --- short-term: session/fixture turns + whatever was typed in the chat box
    stm = ShortTermMemory(strategy="sliding", max_recent_messages=6, pressure_tokens=450)
    for msg in _case_messages(case):
        stm.add(msg["role"], msg["content"])
    for msg in extra_messages:
        stm.add(msg["role"], msg["content"])

    layers = {"short_term": stm.render(), "long_term": "", "episodic": "", "semantic": ""}

    # --- which durable layers this case needs
    expected = case.get("expected_layer", "mixed")
    if expected == "mixed":
        wanted = set(case.get("retrieve_layers") or ["long_term", "semantic"])
    elif expected == "short_term":
        wanted = set()
    else:
        wanted = {expected}
    # Free-form chat is not bound to the case's layer, so widen once the user
    # starts typing — that is what makes this a product rather than a replay.
    if extra_messages:
        wanted |= {"long_term", "episodic", "semantic"}

    if "long_term" in wanted:
        # NOTE: retrieve_long_term calls prime_eval_thread, which DELETES and
        # recreates the thread it is given. Never point it at a seeded session
        # thread (e.g. minh-s1) or the benchmark data is destroyed; use a
        # scratch thread instead. The case's own thread_id is still displayed.
        layers["long_term"] = memory.retrieve_long_term(
            user_id=user_id,
            thread_id=f"ui-scratch-{case['id']}-{user_id}",
            query=query,
        )
    if "episodic" in wanted:
        layers["episodic"] = memory.retrieve_episodic(user_id, query)
    if "semantic" in wanted:
        layers["semantic"] = memory.retrieve_semantic(settings.semantic_graph_id, query)

    merged, breakdown = memory.assemble_context(layers)
    return {"merged_context": merged, "layers": layers, "budget": breakdown}


def _case_messages(case: dict[str, Any]) -> list[dict[str, str]]:
    """Seed turns for the short-term buffer: fixture first, else the real thread."""
    fixture = case.get("fixture_messages")
    if fixture:
        return list(fixture)
    dataset = load_dataset()
    for user in dataset.get("users", []):
        if user["user_id"] != case.get("user_id"):
            continue
        for session in user.get("sessions", []):
            if session["thread_id"] == case.get("thread_id"):
                return list(session.get("messages", []))
    return []


def main() -> None:
    st.set_page_config(page_title="Lab 17 Memory Demo", page_icon="🧠", layout="wide")
    st.markdown(CSS, unsafe_allow_html=True)
    st.title("🧠 Lab 17 — Memory Agent Demo")
    st.caption("Load a test case, inspect layered retrieval, then keep chatting as that user.")

    with st.sidebar:
        st.header("⚙️ Setup")
        zep_ok = bool(settings.zep_api_key)
        st.markdown(("✅" if zep_ok else "⚠️") + " Zep API key "
                    + ("configured" if zep_ok else "missing"))
        llm_ok = openai_available() or gemini_available()
        st.markdown(("✅" if llm_ok else "⚠️") + " Chat LLM key "
                    + ("configured" if llm_ok else "missing"))
        st.caption(f"Chat backend: `{chat_backend()}`")
        st.divider()

        cases = load_cases()
        if not cases:
            st.error("No evaluation cases found.")
            return
        labels = [format_case(c) for c in cases]
        chosen = st.selectbox("Test case", labels)
        case = cases[labels.index(chosen)]

    st.markdown(
        f'<div class="lab-card">{layer_badge(case.get("expected_layer","?"))}'
        f'<b>{case["id"]}</b><br>'
        f'<span class="lab-kv"><b>User:</b> {case.get("user_id","-")} &nbsp;·&nbsp; '
        f'<b>Thread:</b> {case.get("thread_id","-")}</span>'
        f'<p style="margin:.5rem 0 0">{case.get("query","")}</p>'
        f'<span class="lab-kv">{case.get("description","")}</span></div>',
        unsafe_allow_html=True,
    )

    if st.session_state.get("case_id") != case["id"]:
        st.session_state.case_id = case["id"]
        st.session_state.chat = []
        st.session_state.pop("last_result", None)

    col_run, _ = st.columns([1, 3])
    if col_run.button("▶️ Run retrieval on this case", use_container_width=True):
        try:
            memory = StudentMemory(get_zep_client())
            st.session_state.last_result = retrieve_for_case(memory, case, st.session_state.chat)
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)

    result = st.session_state.get("last_result")
    if result:
        st.markdown("### 🔎 Retrieved context")
        active = [k for k, v in result["layers"].items() if v.strip()]
        st.markdown(" ".join(layer_badge(k) for k in active) or "_(nothing retrieved)_",
                    unsafe_allow_html=True)

        if result.get("budget"):
            cols = st.columns(4)
            for i, layer in enumerate(("short_term", "long_term", "episodic", "semantic")):
                b = result["budget"].get(layer, {})
                cols[i].metric(
                    layer,
                    f"{b.get('used_tokens', 0)} tok",
                    help=f"limit {b.get('limit_tokens', 0)} · raw {b.get('raw_tokens', 0)}",
                )

        with st.expander("Merged context (budget-trimmed)", expanded=True):
            st.code(result.get("merged_context") or "(empty)", language="markdown")
        for name, text in result["layers"].items():
            if text.strip():
                with st.expander(f"{name} evidence"):
                    st.write(text)

    st.markdown("### 💬 Continue chat as this user")
    for msg in st.session_state.get("chat", []):
        with st.chat_message(msg["role"]):
            st.write(msg["content"])

    prompt = st.chat_input("Message as this user…")
    if prompt:
        st.session_state.chat.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.write(prompt)
        try:
            memory = StudentMemory(get_zep_client())
            follow = retrieve_for_case(memory, {**case, "query": prompt}, st.session_state.chat)
            st.session_state.last_result = follow
            context = follow.get("merged_context", "")
            if openai_available():
                reply = openai_reply(context, st.session_state.chat[:-1], prompt)
            elif gemini_available():
                reply = generate_reply(context, st.session_state.chat[:-1], prompt)
            else:
                reply = ("_(No chat LLM key — showing retrieved context instead)_\n\n"
                         + (context[:1500] or "(no memory retrieved)"))
            st.session_state.chat.append({"role": "assistant", "content": reply})
            with st.chat_message("assistant"):
                st.write(reply)
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)


if __name__ == "__main__":
    main()
